### ISSUE TITLE
🗺 Navegação

### ISSUE THREAD

**Issue by malkes** [ftrevo/tentacle-android#17]
👧 **Como** usuário do tentacle
**Quero**  poder navegar pela aplicação.
**Para permtir** selecionar abas e ter uma navegação no app 

🎯**Zeplin**
https://app.zeplin.io/project/5c37b147dc351b29912ec627/screen/5c3f87ab5ccaa711410989fb

**Comment by YaraTaciane** [comment]
✨Premissas:

- Home (Listar os últimos 10 games)

- Meus Jogos (Listar todos os jogos cadastrados)

- Biblioteca (Listar todas as mídias)
