### ISSUE TITLE
[  🙇‍♂️ Login #2]

### ISSUE THREAD

**Issue by beugenio** [ftrevo/tentacle-android#2]
User Story
Como um usuário do tentacle
Quero ser capaz de me logar na plataforma
Para permitir o acesso na plataforma.

Premissas:
- Precisa ser um email valido.
- A senha deve ter no minimo 5 caracters.
[] testes

Swagger
https://tentacle-backend.herokuapp.com/swagger/#/Access/post_login

Zeplin
https://app.zeplin.io/project/5c06c267baf8262fc531526f/screen/5c0985876733bab83d41a29f

**Comment by YaraTaciane** [comment]
> 🛴  Prioridade **1**
