### ISSUE TITLE
[👨‍🚀Push notifications #403]

### ISSUE THREAD

**Issue by ftrevo** [ftrevo/tentacle-android#403]
👨‍🚀Como usuário do Tentacle 
Gostaria de receber mensagens 
Para sinalizar ações ações ocorridas com jogos do meu interesse

**Critérios de Aceite**: 

- Fazer o controle de tokens do firebase para podermos utilizar notificações no app.

- O token do device do usuário deve ser informado no momento do Login e do Cadastro do usuário (nome do campo: deviceToken).

- Caso possível, seria interessante mas não obrigatório para agora o app notificar o backend no momento em que o firebase notificar qualquer alteração do token.

Ver documentação para mais detalhes.
https://firebase.google.com/docs/cloud-messaging/android/client?hl=pt-br

**Comment by YaraTaciane** [comment]
🛠 **Para ajustar (Nova Definição)**

Quando o usuário logar e após a criação de novo usuário será feita uma requisição em background para a rota /device-token onde essa rota será responsável enm associar o token ao usuário logado
E o app vai ter a parte de 'escutar' o FCM, onde caso o usuário logue ou seja criado e o FCM ainda não respondeu, a requisição acima citada não sera enviada, só será enviada após o FCM responder, logo, com o usuário já autenticado

O mesmo serve para o refresh-token, ao fazer o refresh, em background vai mandar a requisição do device-token
