### ISSUE TITLE
[🤸‍♀️  Redirecionar usuário a tela de Login #498]

### ISSUE THREAD

**Issue by ftrevo** [ftrevo/tentacle-android#498]
👀 Tem dependência com a [🧙‍♂️ Renovação de token #3]

Ao receber erro 401, tentar realizar o refresh-token, caso ele não tenha sucesso, redirecionar o usuário para a tela de Login

**Comment by malkes** [comment]
Tarefa foi feita junto com a 3_US_Refresh_Token
