### ISSUE TITLE
🐱‍💻 Cadastrar jogos : O usuário adiciona os jogos que quer disponibilizar na plataforma

### ISSUE THREAD

**Issue by beugenio** [ftrevo/tentacle-android#5]
👧 User Story
**Como** um usuário do tentacle
**Quero ser capaz** de cadastrar um jogo na plataforma
**Para permitir** que o jogo seja emprestado posteriormente.

**Premissas:**
- Para cadastrar um jogo, o usuário deve informar a descrição do jogo em seguinda a aplicação lista todos os jogos cadastrados de acordo com a consulta. 
- O usuário pode selecionar um jogo já cadastrado ou adicionar um novo caso não exista.
- Após selecionar o jogo ou cadastrar um novo o usuário deve selecionar a plataforma.
- Nesse primeiro momento não iremos integrar o tentacle com nenhuma base de dados de jogos(isto vai ser feito posteriormente).
- Para desativar um jogo na plataforma 

🎯**Zeplin**
https://app.zeplin.io/project/5c37b147dc351b29912ec627/screen/5c38ca0d6d33c3bee3877433
https://app.zeplin.io/project/5c37b147dc351b29912ec627/screen/5c38ca0e17b58ebe2a6fd142
https://app.zeplin.io/project/5c37b147dc351b29912ec627/screen/5c38ca0dcc7204be8f947e27

CustomView 
🐱‍🚀 Tarefas do Time:  
- Buscar e Listar jogos do server 
- Cadastro de Media
- Lista dos Jogos que não estão na nossa base

**Comment by YaraTaciane** [comment]
> 🛴  Prioridade **3**

✨Premissas : 

- Cadastrado em única tela (jogos ou mídia)
- Tratar jogo duplicado (no front)
- Não terá auto-complete
